In [651]:
#importing libraries
import pandas as pd
import numpy as np
import selenium
import time
from bs4 import BeautifulSoup

#Importing requests
import requests

#importing selenium webdriver
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#import plotty
import warnings
warnings.filterwarnings('ignore')

In [606]:
# Extracting the path of the webdriver
PATH = 'C:/Users/hp-pc/Downloads/chromedriver_win32/chromedriver'
driver = webdriver.Chrome(PATH)

Q1:-  Write a python program which searches all the product under a particular product from www.amazon.in. 
The product to be searched will be taken as input from user. For e.g. If user input is ‘guitar’. Then search 
for guitars?

In [607]:
url = 'https://www.amazon.in/'  #Open the website by using driver.get
driver.get(url)

time.sleep(5) #time delay of 5 seconds

input = driver.find_element_by_id('twotabsearchtextbox') #Send the keys to the search bar
input.send_keys('T shirt')

time.sleep(2) #time delay of 2 seconds

search_btn = driver.find_element_by_id('nav-search-submit-button') #pressing search button to search the product
search_btn.click()

Q2:- In the above question, now scrape the following details of each product listed in first 3 pages of your search results and save it in a data frame and csv. In case if any product has less than 3 pages in search results then scrape all the products available under that product name.

In case, if any of the details are missing for any of the product then replace it by “-“.

Details to be scraped are:
1. Brand Name
2. Name of the product
3. Price
4. Return/Exchange
5. Expected Delivery
6. Availability
7. Product URL

In [608]:
#Creating empty lists for storing the data
brand_name = []
name_product = []
price = []
ret_exc = []
exp_del = []
avail = []
#pro_url = []

#scrapping the required details
start=0
end=3
for page in range(start,end):#for loop for scrapping 4 page

    try:
        bn = driver.find_elements_by_xpath("//*[@class='a-size-base-plus a-color-base']")
        for i in bn:
            brand_name.append(i.text)
    except NoSuchElementException:
        brand_name.append('-')

# Extracting price and saving it into price list
    try:
        p = driver.find_elements_by_xpath("//span[@class='a-price']")
        for i in p:
            price.append(i.text)
    except:
        price.append('-')
# Extracting product name and saving it into name_product list
    try:
        pn = driver.find_elements_by_xpath("//*[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']")
        for i in pn:
            name_product.append(i.text)
    except:
        name_product.append('-')
        


        
    nxt_button=driver.find_elements_by_xpath("//a[@class='s-pagination-item s-pagination-next s-pagination-button s-pagination-separator']")
    #scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [612]:
df_products=pd.DataFrame({'Brand_name': brand_name,
                'Price': price,
               'Product_name': name_product })
df_products

                Brand_name Price                                  Product_name
0      Scott International  ₹449         Men's Regular Fit T-Shirt (Pack of 3)
1      Scott International  ₹449         Men's Regular Fit T-Shirt (Pack of 3)
2    Van Heusen Athleisure  ₹549               Men's Solid Regular fit T-Shirt
3    Van Heusen Athleisure  ₹849                                   Men T-Shirt
4                EYEBOGLER  ₹299  Men's Regular Fit Striped Round Neck T-Shirt
..                     ...   ...                                           ...
166          AMERICAN CREW  ₹649                     Men's Regular Fit T-Shirt
167  Van Heusen Athleisure  ₹849                                   Men T-Shirt
168                    R&B  ₹319                Men Regular Sleeveless T-Shirt
169                   Puma  ₹899            Men T-Shirt Classics Graphics Camo
170               Boodbuck  ₹899       Printed T Shirt for Men Combo Pack of 3

[171 rows x 3 columns]

Q4:- Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on
www.flipkart.com and scrape following details for all the search results displayed on 1st page. Details to be 
scraped: “Brand Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”, 
“Secondary Camera”, “Display Size”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the 
details is missing then replace it by “- “. Save your results in a dataframe and CSV.

In [ ]:
# Extracting the path of the webdriver
PATH = 'C:/Users/hp-pc/Downloads/chromedriver_win32/chromedriver'
driver = webdriver.Chrome(PATH)

In [615]:
url = 'https://www.flipkart.com/'  #Open the website by using driver.get
driver.get(url)

time.sleep(5) #time delay of 5 seconds
try:
    cross_btn = driver.find_element_by_xpath('//button[@class="_2KpZ6l _2doB4z"]').click() 
except NoSuchElementException:
    pass
    
time.sleep(1)
input = driver.find_element_by_xpath('//input[@class="_3704LK"]') #Send the keys to the search bar
input.send_keys('smartphone')

time.sleep(2) #time delay of 2 seconds

search_btn = driver.find_element_by_xpath('//button[@class="L0Z3Pu"]')
search_btn.click()

In [627]:
#Creating Empty list
brand_name=[]
smartphone_name=[]
colour=[]
RAM =[]
ROM=[]
Primary_camera=[]
Secondary_camera=[]
Display_size=[]
Battery_capacity=[]
price=[]
product_URL=[]
full_text=[]


#fetching product urls
for i in driver.find_elements_by_xpath("//a[@class='_1fQZEK']"):
    product_URL.append(i.get_attribute('href'))
    
for i in product_URL:
    driver.get(i)
    time.sleep(2)
    
#Fetching price and saving it into the price list
    try:
        price1 = driver.find_elements_by_xpath("//*[@class='_30jeq3 _1_WHN1']")
        for i in price1:
            price.append(i.text)
    except:
         price.append('-')
    
        
    
# Clicking readmore button   
    read_more_button = driver.find_element_by_xpath('//button[@class="_2KpZ6l _1FH0tX"]') #pressing search button to search the product
    read_more_button.click()
    time.sleep(2)
#fetching the whole table into one list    
    table = driver.find_elements_by_xpath("//*[@class='_1s_Smc row']")
# putting the text value into 'name'
    for name in table:
        full_text=name.find_element_by_xpath("td[1]").text
        
        # Extracting Model name and saving it into smartphone list
        try:
            if full_text=='Model Name':
                smartphone_name.append(name.find_element_by_xpath("td[2]").text)
        except:
            smartphone_name.append('-')
        # Extracting Colour and saving it into smartphone list    
        try:
            if full_text=='Color':
                colour.append(name.find_element_by_xpath("td[2]").text)
        except:
            colour.append('-')
        # Extracting Internal Storage and saving it into smartphone list
        try:
            if full_text=='Internal Storage':
                ROM.append(name.find_element_by_xpath("td[2]").text)
        except:
            ROM.append('-')
        # Extracting RAM and saving it into smartphone list
        try:
            if full_text=='RAM':
                RAM.append(name.find_element_by_xpath("td[2]").text)
        except:
            RAM.append('-')
        # Extracting Primary camera and saving it into smartphone list
        try:
            if full_text=='Primary Camera':
                Primary_camera.append(name.find_element_by_xpath("td[2]").text)
        except:
            Primary_camera.append('-')
        # Extracting Secondary camera and saving it into smartphone list
        try:
            if full_text=='Secondary Camera':
                Secondary_camera.append(name.find_element_by_xpath("td[2]").text)
        except:
            Secondary_camera.append('-')
        # Extracting Display size and saving it into smartphone list
        try:
            if full_text=='Display Size':
                Display_size.append(name.find_element_by_xpath("td[2]").text)
        except:
            Display_size.append('-')

In [633]:
df =pd.DataFrame({
                'Smartphone_name': smartphone_name,
               'Colour': colour,
                'Internal_storage': ROM,
                'Primary_camera': Primary_camera,
                'Secondary_camera': Secondary_camera,
                'Display_size':Display_size,
                  })
df

,Smartphone_name,Colour,Internal_storage,Primary_camera,Secondary_camera,Display_size
0,C21Y,Cross Blue,32 GB,13MP + 2MP + 2MP,5MP Front Camera,16.51 cm (6.5 inch)
1,C21Y,Cross Blue,64 GB,13MP + 2MP + 2MP,5MP Front Camera,16.51 cm (6.5 inch)
2,C21Y,Cross Black,32 GB,13MP + 2MP + 2MP,5MP Front Camera,16.51 cm (6.5 inch)
3,C21Y,Cross Black,64 GB,13MP + 2MP + 2MP,5MP Front Camera,16.51 cm (6.5 inch)
4,Narzo 50A,Oxygen Blue,64 GB,50MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch)
5,Narzo 50A,Oxygen Blue,128 GB,50MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch)
6,Narzo 50A,Oxygen Green,64 GB,50MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch)
7,Narzo 50A,Oxygen Green,128 GB,50MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch)
8,9i,Sea Blue,64 GB,13MP Rear Camera,5MP Front Camera,16.59 cm (6.53 inch)
9,9i,Nature Green,64 GB,13MP Rear Camera,5MP Front Camera,16.59 cm (6.53 inch)
10,9i Sport,Coral Green,64 GB,13MP Rear Camera,5MP Front Camera,16.59 cm (6.53 inch)
11,9i,Midnight Black,64 GB,13MP Rear Camera,5MP Front Camera,16.59 cm (6.53 inch)
12,C11 2021,Cool Grey,32 GB,8MP Rear Camera,5MP Front Camera,16.51 cm (6.5 inch)
13,M3,Yellow,64 GB,48MP + 2MP + 2MP,8MP Front Camera,16.59 cm (6.53 inch)
14,C25_Y,Metal Grey,64 GB,50MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch)
15,C25_Y,Glacier Blue,64 GB,50MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch)
16,C25Y,Metal Grey,64 GB,50MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch)
17,iPhone 12 Mini,Black,64 GB,12MP + 12MP,12MP Front Camera,13.72 cm (5.4 inch)
18,C11 2021,Cool Blue,32 GB,8MP Rear Camera,5MP Front Camera,16.51 cm (6.5 inch)
19,C11 2021,Cool Grey,64 GB,8MP Rear Camera,5MP Front Camera,16.51 cm (6.5 inch)
20,C11 2021,Cool Blue,64 GB,8MP Rear Camera,5MP Front Camera,16.51 cm (6.5 inch)
21,8s 5G,Universe Purple,128 GB,64MP + 2MP + 2MP,16MP Front Camera,16.51 cm (6.5 inch)
22,C25Y,Metal Grey,128 GB,50MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch)
23,C25Y,Glacier Blue,128 GB,50MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch)

Q5:- Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google
maps?

In [ ]:
url = 'https://www.google.co.in/maps'  #Open the website by using driver.get
driver.get(url)

time.sleep(5) #time delay of 5 seconds

input = driver.find_element_by_xpath('//input[@class="tactile-searchbox-input"]') #Send the keys to the search bar
input.send_keys('Haridwar')

time.sleep(2) #time delay of 2 seconds

search_btn = driver.find_element_by_xpath('//button[@id="searchbox-searchbutton"]') #pressing search button to search the product
search_btn.click()

Q6:- Write a program to scrap details of all the funding deals for second quarter (i.e Jan 21 – March 21) 
from trak.in.

In [634]:
url = 'https://trak.in/'  #Open the website by using driver.get
driver.get(url)

#time.sleep(5) #time delay of 5 seconds

# input = driver.find_element_by_xpath('//input[@class="tactile-searchbox-input"]') #Send the keys to the search bar
# input.send_keys('Haridwar')

time.sleep(2) #time delay of 2 seconds

search_btn = driver.find_element_by_xpath('//*[@class="menu-have-icon menu-icon-type-fontawesome menu-item menu-item-type-post_type menu-item-object-page better-anim-fade menu-item-51510"]//a//i') #pressing search button to search the product
search_btn.click()

In [635]:
#creating empty list

date=[]
st_nme=[]
ind=[]
sub_ver=[]
city=[]
inv_nme=[]
inv_type=[]
amount=[]

#Dates
# January month
try:
    dt = driver.find_elements_by_xpath("//*[@id='tablepress-54']//tbody//tr//td[2]")
    for i in dt:
        date.append(i.text)
except:
    date.append('-')
# february month
try:
    dt = driver.find_elements_by_xpath("//*[@id='tablepress-55']//tbody//tr//td[2]")
    for i in dt:
        date.append(i.text)
except:
    date.append('-')
# march month
try:
    dt = driver.find_elements_by_xpath("//*[@id='tablepress-56']//tbody//tr//td[2]")
    for i in dt:
        date.append(i.text)
except:
    date.append('-')    
#Startup name  
# january month
try:
    st = driver.find_elements_by_xpath("//*[@id='tablepress-54']//tbody//tr//td[3]")
    for i in st:
        st_nme.append(i.text)
except:
    st_nme.append('-')
# february month
try:
    st = driver.find_elements_by_xpath("//*[@id='tablepress-55']//tbody//tr//td[3]")
    for i in st:
        st_nme.append(i.text)
except:
    st_nme.append('-')
# march month
try:
    st = driver.find_elements_by_xpath("//*[@id='tablepress-56']//tbody//tr//td[3]")
    for i in st:
        st_nme.append(i.text)
except:
    st_nme.append('-')  

#Industry  
# january month
try:
    indus = driver.find_elements_by_xpath("//*[@id='tablepress-54']//tbody//tr//td[4]")
    for i in indus:
        ind.append(i.text)
except:
    ind.append('-')
# february month
try:
    indus = driver.find_elements_by_xpath("//*[@id='tablepress-55']//tbody//tr//td[4]")
    for i in indus:
        ind.append(i.text)
except:
    ind.append('-')
# march month
try:
    indus = driver.find_elements_by_xpath("//*[@id='tablepress-56']//tbody//tr//td[4]")
    for i in indus:
        ind.append(i.text)
except:
    ind.append('-') 

#Sub-vertical 
# january month
try:
    sv = driver.find_elements_by_xpath("//*[@id='tablepress-54']//tbody//tr//td[5]")
    for i in sv:
        sub_ver.append(i.text)
except:
    sub_ver.append('-')
# february month
try:
    sv = driver.find_elements_by_xpath("//*[@id='tablepress-55']//tbody//tr//td[5]")
    for i in sv:
        sub_ver.append(i.text)
except:
    sub_ver.append('-')
# march month
try:
    sv = driver.find_elements_by_xpath("//*[@id='tablepress-56']//tbody//tr//td[5]")
    for i in sv:
        sub_ver.append(i.text)
except:
    sub_ver.append('-')  

#city  
# january month
try:
    c = driver.find_elements_by_xpath("//*[@id='tablepress-54']//tbody//tr//td[6]")
    for i in c:
        city.append(i.text)
except:
    city.append('-')
# february month
try:
    c = driver.find_elements_by_xpath("//*[@id='tablepress-55']//tbody//tr//td[6]")
    for i in c:
        city.append(i.text)
except:
    city.append('-')
# march month
try:
    c = driver.find_elements_by_xpath("//*[@id='tablepress-56']//tbody//tr//td[6]")
    for i in c:
        city.append(i.text)
except:
    city.append('-') 

#investor's name  
# january month
try:
    inv = driver.find_elements_by_xpath("//*[@id='tablepress-54']//tbody//tr//td[7]")
    for i in inv:
        inv_nme.append(i.text)
except:
    inv_nme.append('-')
# february month
try:
    inv = driver.find_elements_by_xpath("//*[@id='tablepress-55']//tbody//tr//td[7]")
    for i in inv:
        inv_nme.append(i.text)
except:
    inv_nme.append('-')
# march month
try:
    inv = driver.find_elements_by_xpath("//*[@id='tablepress-56']//tbody//tr//td[7]")
    for i in inv:
        inv_nme.append(i.text)
except:
    inv_nme.append('-')  

    
#Investment type 
# january month
try:
    invt = driver.find_elements_by_xpath("//*[@id='tablepress-54']//tbody//tr//td[8]")
    for i in invt:
        inv_type.append(i.text)
except:
    inv_type.append('-')
# february month
try:
    invt = driver.find_elements_by_xpath("//*[@id='tablepress-55']//tbody//tr//td[8]")
    for i in invt:
        inv_type.append(i.text)
except:
    inv_type.append('-')
# march month
try:
    invt = driver.find_elements_by_xpath("//*[@id='tablepress-56']//tbody//tr//td[8]")
    for i in invt:
        inv_type.append(i.text)
except:
    inv_type.append('-')  

    
#Amount 
# january month
try:
    amt = driver.find_elements_by_xpath("//*[@id='tablepress-54']//tbody//tr//td[9]")
    for i in amt:
        amount.append(i.text)
except:
    amount.append('-')
# february month
try:
    amt = driver.find_elements_by_xpath("//*[@id='tablepress-55']//tbody//tr//td[9]")
    for i in amt:
        amount.append(i.text)
except:
    amount.append('-')
# march month
try:
    amt = driver.find_elements_by_xpath("//*[@id='tablepress-56']//tbody//tr//td[9]")
    for i in amt:
        amount.append(i.text)
except:
    amount.append('-')  
    
# #Combining all the lists into a single dataframe
df_funding_deals=pd.DataFrame({'Date': date,
                'Startup_name': st_nme,
               'Industry/Vertical': ind,
                'Sub Vertical': sub_ver,
                'City': city,
                'Investors_name': inv_nme,
                'Inverstors_type': inv_type,
                'Amount(in USD)':amount
                       })
df_funding_deals.head()

,Date,Startup_name,Industry/Vertical,Sub Vertical,City,Investors_name,Inverstors_type,Amount(in USD)
0,15/01/2021,Digit Insurance,Financial Services,Insurance Services,Bengaluru,"A91 Partners, Faering Capital, TVS Capital Funds",Venture,"1,80,00,000"
1,28/01/2021,Bombay Shaving Company,Consumer Goods Company,"Shave care, beard care, and skincare products",New Delhi,Reckitt Benckiser,Venture,"6,172,258.50"
2,19/01/2021,DeHaat,AgriTech Startup,online marketplace for farm products and services,Patna,Prosus Ventures,Series C,"30,000,000"
3,19/01/2021,Darwinbox,SaaS,HR Tech,Mumbai,Salesforce Ventures,Seed,"15,000,000"
4,18/01/2021,mfine,Health Tech Startup,AI-powered telemedicine mobile app,Bengaluru,Heritas Capital Management,Venture Round,"16,000,000"

Q7:- Write a program to scrap all the available details of best gaming laptops from digit.in.

In [ ]:
# Extracting the path of the webdriver
PATH = 'C:/Users/hp-pc/Downloads/chromedriver_win32/chromedriver'
driver = webdriver.Chrome(PATH)

In [636]:
url = 'https://www.digit.in/'  #Open the website by using driver.get
driver.get(url)

#time.sleep(5) #time delay of 5 seconds

# input = driver.find_element_by_xpath('//div[@class="listing_container"]//li[9]') #Send the keys to the search bar
# input.send_keys('Har')

time.sleep(2) #time delay of 2 seconds

search_btn = driver.find_element_by_xpath('//div[@class="listing_container"]//li[9]') #pressing search button to search the product
search_btn.click()

In [637]:
#creating empty list

prod_name = []
opr_sys=[]
dis_size=[]
processor=[]
memory=[]
weight=[]
dim=[]
grp_pr=[]
seller=[]
price1=[]
# # fetching product name
try:
    pn = driver.find_elements_by_xpath('//*[@class="right-container"]//div//a//h3')
    for i in pn:
        prod_name.append(i.text)
except:
    prod_name.append('-')

# fetching operating system
try:
    os = driver.find_elements_by_xpath('//*[text()="OS" ]//..//td[3]')
    for i in os:
        opr_sys.append(i.text)
except:
    opr_sys.append('-')
# fetching Display size 
try:
    ds = driver.find_elements_by_xpath("//*[text()='Display' ]//..//td[3]")
    for i in ds:
        dis_size.append(i.text)
except:
    dis_size.append('-')

# fetching processor
try:
    pr = driver.find_elements_by_xpath("//*[text()='Processor' ]//..//td[3]")
    for i in pr:
        processor.append(i.text)
except:
    processor.append('-')
# fetching memory
try:
    mm = driver.find_elements_by_xpath("//*[text()='Memory' ]//..//td[3]")
    for i in mm:
        memory.append(i.text)
except:
    memory.append('-')
       
# fetching weight
try:
    wgt = driver.find_elements_by_xpath("//*[text()='Weight' ]//..//td[3]")
    for i in wgt:
        weight.append(i.text)
except:
    weight.append('-')

# fetching weight 
try:
    d = driver.find_elements_by_xpath("//*[text()='Dimension' ]//..//td[3]")
    for i in d:    
        dim.append(i.text)
except:
    dim.append('-')
# fetching Graphics processor
try:
    gp = driver.find_elements_by_xpath("//*[text()='Graphics Processor' ]//..//td[3]")
    for i in gp:    
        grp_pr.append(i.text)
except:
    grp_pr.append('-')
    
# #fetching seller
try:
    s = driver.find_elements_by_xpath('//*[@class="smmerchant"]')
    for i in s:    
        seller.append(i.text)
except:
    seller.append('-')


#fetching price
try:
    prices = driver.find_elements_by_xpath('//*[@class="smprice"]')
    for i in prices:    
        price1.append(i.text)
except:
    price1.append('-')
    
    


# #Combining all the lists into a single dataframe
df_laptop=pd.DataFrame({'Product_name': prod_name,
                'Operating system': opr_sys,
               'Display_size': dis_size,
                'Processor': processor,
                'Memory': memory,
                'Weight': weight,
                'Dimension': dim,
                'Group_processor':grp_pr,
                'Seller': seller,
                'Price': price1
                       })
df_laptop

,Product_name,Operating system,Display_size,Processor,Memory,Weight,Dimension,Group_processor,Seller,Price
0,ACER NITRO 5 RYZEN 9 (2021),Windows 10,"15.6"" (1920 x 1080)",AMD Ryzen 9 Octa Core | 2.4 GHz,1 TB HDD/16 GBGB DDR4,2.4,363.4 x 255 x 23.9,NVIDIA GeForce RTX 3070,Flipkart,"₹ 129,990"
1,MSI STEALTH 15M 11TH GEN CORE I7-11375H (2021,Windows 10,"15.6"" (1920 x 1080)",Intel Core i7 11th Gen - 11375H | NA,1 TB SSD/16 GBGB DDR4,1.7,358.3 x 248 x 16.15,NVIDIA GeForce RTX 3060,Flipkart,"₹ 134,990"
2,ASUS ROG STRIX SCAR 15 RYZEN 9-5900HX (2021),Windows 10,"15.6"" (2560 x 1440)",AMD Ryzen 9 Octa Core - 5900HX | 3.3 GHz,2 TB SSD/32 GBGB DDR4,2.30,354 x 259 x 22.6,NVIDIA GeForce RTX 3080,Flipkart,"₹ 268,990"
3,ALIENWARE AREA 51M R2,Windows 10 Home,"17.3"" (1920 x 1080)",10th Gen Intel® Core™ i7-10700 | 2.90 GHz,1 TB SSD/16 GBGB DDR4,4.1,27.65 x 402.6 x 319.14,Intel® UHD Graphics 630,N/A,"₹ 342,989"
4,ALIENWARE M15 R3,Windows 10 Home,"15.6"" (3840 x 2160)",10th Gen Intel® Core™ i9-10980HK | NA,1 TB SSD/16 GBGB DDR4,NA,NA,NA,Amazon,"₹ 319,990"
5,ASUS ROG STRIX SCAR 15,Windows 10 Home,"15.6"" (1920 x 1080)",AMD Ryzen™ 9 5900HX | 3.3 GHz,1 TB SSD/16 GBGB DDR4,2.30,35.4 x 25.9 x 2.26,NVIDIA® GeForce RTX™ 3070,Flipkart,"₹ 215,990"
6,ASUS ROG ZEPHYRUS G14,Windows 10 Home,"14"" (1920 x 1080)",AMD 3rd Gen Ryzen 9 | 3.3 GHz,1 TB SSD/16 GBGB DDR4,1.65,32.5 x 22.1 x 1.8,NVIDIA GeForce RTX 2060,Amazon,"₹ 164,990"
7,LENOVO LEGION 5I,Windows 10 Pro,"15.6"" (1920 x 1080)",10th Gen Intel® Core™ i5-10300H | 2.50 GHz,1 TB SSD/16 GBGB DDR4,2.3,363.06 x 259.61 x 23.57,NVIDIA® GeForce® GTX 1650 4GB,Amazon,"₹ 76,988"
8,ASUS ROG ZEPHYRUS DUO 15,Windows 10,"15.6"" (3840 x 1100)",Intel Core i7 10th Gen 10875H | NA,512 GB SSD/4 GBGB DDR4,2.4,268.30 x 360.00 x 20.90,NVIDIA GeForce RTX 2070 Max-Q,Amazon,"₹ 185,000"
9,ACER ASPIRE 7 GAMING,Windows 10 Home,"15.6"" (1920 x 1080)",AMD Ryzen™ 5-5500U hexa-core | NA,512 GB SSD/8 GBGB DDR4,2.15,2.29 x 36.3 x 25.4,NVIDIA® GeForce® GTX 1650,Amazon,"₹ 58,465"

Q8:- Write a python program to scrape the details for all billionaires from www.forbes.com.

Details to be scrapped:
1. Rank
2. Name
3. Net Worth
4. Age
5. Citizenship
6. Source
7. Industry

In [652]:
# Extracting the path of the webdriver
PATH = 'C:/Users/hp-pc/Downloads/chromedriver_win32/chromedriver'
driver = webdriver.Chrome(PATH)

In [639]:
url = 'https://www.forbes.com/?sh=1d51f0a02254'  #Open the website by using driver.get
driver.get(url)

time.sleep(2) #time delay of 2 seconds

click_btn = driver.find_element_by_xpath('//button[@class="icon--hamburger"]') #pressing search button to search the product
click_btn.click()

time.sleep(2)

click_btn1 = driver.find_element_by_xpath('//a[@class="header__title"]') #pressing search button to search the product
click_btn1.click()

time.sleep(2)

click_btn2 = driver.find_element_by_xpath('//h2[@class="chansec-special-feature__title no-label--special-feature"]') #pressing search button to search the product
click_btn2.click()

In [640]:
# Creating empty list
pnme=[]
rank=[]
net_worth=[]
age=[]
citizenship=[]
source =[]
industry = []
# fetching rank
try:
    rnk = driver.find_elements_by_xpath("//div[@class='rank']")
    for i in rnk:
        rank.append(i.text)
except:
    rank.append('-')
#fetching person name
try:
    pn = driver.find_elements_by_xpath("//div[@class='personName']")
    for i in pn:
        pnme.append(i.text)
except:
    pnme.append('-')
# fetching net worth    
try:
    nw = driver.find_elements_by_xpath("//div[@class='netWorth']")
    for i in nw:
        net_worth.append(i.text)
except:
    net_worth.append('-')
#fetching age
try:
    a = driver.find_elements_by_xpath("//div[@class='age']")
    for i in a:
        age.append(i.text)
except:
    age.append('-')
# fetching citizenship
try:
    ct = driver.find_elements_by_xpath("//div[@class='countryOfCitizenship']")
    for i in ct:
        citizenship.append(i.text)
except:
    citizenship.append('-')
#fetching source
try:
    s = driver.find_elements_by_xpath("//div[@class='source-column']")
    for i in s:
        source.append(i.text)
except:
    source.append('-')
#fetching industry
try:
    ind = driver.find_elements_by_xpath("//div[@class='category']")
    for i in ind:
        industry.append(i.text)
except:
    industry.append('-')

#Combining all the lists into a single dataframe
df_billionaries=pd.DataFrame({'Rank': rank,
                'Person_Name': pnme,
               'Net_Worth': net_worth,
                'Age': age,
                'Citizenship': citizenship,
                'Source': source,
                'Industry': industry})
df_billionaries

,Rank,Person_Name,Net_Worth,Age,Citizenship,Source,Industry
0,1.,Jeff Bezos,$177 B,57,United States,Amazon,Technology
1,2.,Elon Musk,$151 B,49,United States,"Tesla, SpaceX",Automotive
2,3.,Bernard Arnault & family,$150 B,72,France,LVMH,Fashion & Retail
3,4.,Bill Gates,$124 B,65,United States,Microsoft,Technology
4,5.,Mark Zuckerberg,$97 B,36,United States,Facebook,Technology
...,...,...,...,...,...,...,...
195,195.,Harry Triguboff,$11.2 B,88,Australia,real estate,Real Estate
196,197.,Leonid Fedun & family,$11.1 B,65,Russia,oil,Energy
197,197.,Eyal Ofer,$11.1 B,70,Israel,"real estate, shipping",Diversified
198,197.,Evan Spiegel,$11.1 B,30,United States,Snapchat,Technology
199,200.,Luis Carlos Sarmiento,$11 B,88,Colombia,banking,Finance & Investments

Q9:-  Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted from any YouTube Video.

In [653]:
url = 'https://www.youtube.com/'  #Open the website by using driver.get
driver.get(url)

time.sleep(5) #time delay of 5 seconds

#input = driver.find_element_by_xpath('//input[@id="location-text-input-field"]')
input = driver.find_element_by_xpath('//input[@id="search"]')#Send the keys to the search bar
input.send_keys('param sundari')

time.sleep(2)

search_btn = driver.find_element_by_xpath('//button[@id="search-icon-legacy"]') #pressing search button to search the product
search_btn.click()

time.sleep(2)

search_btn = driver.find_element_by_xpath('//h3[@class="title-and-badge style-scope ytd-video-renderer"]') #pressing search button to search the product
search_btn.click()

In [661]:
#creating empty list
comment=[]
comment_upvote=[]
time=[]

#fetching comments
cycle = 100
for i in range(cycle):
    try:
        com = driver.find_elements_by_xpath('//*[@id="content-text"]')
        for i in com:
            comment.append(i.text.replace('\n',''))
    except:
        comment.append('-')
        
#fetching comments upvoted
cycle = 100
for i in range(cycle):
    try:
        com_up = driver.find_elements_by_xpath('//*[@id="vote-count-middle"]')
        for i in com_up:
            comment_upvote.append(i.text.replace('\n',''))
    except:
        comment_upvote.append('-')
        
# fetching time
cycle = 100
for i in range(cycle):
    try:
        t = driver.find_elements_by_xpath('//*[@class="published-time-text above-comment style-scope ytd-comment-renderer"]')
        for i in t:
            time.append(i.text.replace('\n',''))
    except:
        time.append('-')
        
#Combining all the lists into a single dataframe
df_youtube=pd.DataFrame({'Comments': comment,
                'Comments_upvoted': comment_upvote,
               'Time': time,
                })
print("\t\t\tParam Sundari- Official Video")
df_youtube

			Param Sundari- Official Video

,Comments,Comments_upvoted,Time
0,Shreya Ghoshal singing for ARR is a gift to ou...,138K,5 months ago
1,"So good to hear an original melodious song, th...",14K,5 months ago
2,Voice of Shreya Ghoshal🔥 Dancing of Kriti Sanon🔥,398,1 month ago (edited)
3,"What a great chorus, Additional vocals are : S...",268,1 month ago (edited)
4,Who's watching it in 2022.?.. 💥..It will soon ...,134,2 days ago
...,...,...,...
1995,Shreya's Voice +Kriti's Dance = 🔥🔥🔥,281,7 days ago
1996,Vera level song ❤️ ar rahman Sir good music ❤️...,8,3 days ago
1997,I can't stop listening to this song every time...,93,1 month ago
1998,Now I can't start day without listen to this m...,14,3 days ago
1999,A.R. Rahman is the backbone of Indian music in...,1.2K,5 months ago

10. Write a python program to scrape a data for all available Hostels from https://www.hostelworld.com/ in 
“London” location. You have to scrape hostel name, distance from city centre, ratings, total reviews, 
overall reviews, privates from price, dorms from price, facilities and property description

In [664]:
url = "https://www.hostelworld.com/s?q=London,%20England&country=England&city=London&type=city&id=3&from=2022-01-03&to=2022-01-06&guests=2&page=1"
driver.get(url)

In [ ]:
# creating empty list
hostel_name=[]
dist_city=[]
rating=[]
total_reviews=[]
overall_reviews=[]
privates_price=[]
dorm_prices=[]
facilities =[]
pro_des=[]
urls=[]

start=0
end=4
for page in range(start, end):#for loop for scrapping 4 page
#fetching product urls
   
    try:
        hn = driver.find_elements_by_xpath('//*[@class="title title-6"]')
        for i in hn:
            hostel_name.append(i.text)
    except:
        hostel_name.append('-')
        
    try:
        dc = driver.find_elements_by_xpath('//*[@class="description"]')
        for i in dc:
            dist_city.append(i.text)
    except:
        dist_city.append('-')
        
    try:
        rt = driver.find_elements_by_xpath('//*[@class="reviews"]')
        for i in rt:
            total_reviews.append(i.text)
    except NoSuchElementException:
        total_reviews.append('-')
        
    try:
        f = driver.find_elements_by_xpath('//*[@class="rating-factors prop-card-tablet rating-factors small"]')
        for i in f:
            facilities.append(i.text)
    except NoSuchElementException:
        facilities.append('-')


        
    try:
        nxt_button=driver.find_element_by_xpath("//div[@class='pagination-item pagination-next']").click()#scraping the list of buttons from the page
        start+=1
    except NoSuchElementException:
        pass

    
    
    
df= pd.DataFrame({
                 'hostel_name': hostel_name,
                 'Distance from city centre': dist_city,
                 'total reviews': total_reviews,
                 'facilities': facilities
                })
df